// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package form

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func InputImage(label, name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"sm:col-span-full\"><label for=\"cover-photo\" class=\"block text-sm font-medium leading-6 text-gray-900\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(label)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/form/image.templ`, Line: 4, Col: 92}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label><div id=\"drop-zone\" class=\"mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10\"><div class=\"text-center\"><!-- Placeholder for the SVG or image preview --><div class=\"w-full flex items-center justify-center\"><div id=\"image-preview\" class=\"w-20 aspect-square flex items-center justify-center\"><svg class=\"mx-auto h-12 w-12 text-gray-300\" viewBox=\"0 0 24 24\" fill=\"currentColor\" aria-hidden=\"true\"><path fill-rule=\"evenodd\" d=\"M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z\" clip-rule=\"evenodd\"></path></svg></div></div><div class=\"mt-4 flex text-sm leading-6 text-gray-600\"><label for=\"file-upload\" class=\"relative cursor-pointer rounded-md bg-white font-semibold text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 hover:text-indigo-500\"><span>Upload a file</span> <input size=\"500\" id=\"file-upload\" name=\"file-upload\" type=\"file\" class=\"sr-only\" accept=\".svg\"></label></div><p class=\"text-xs leading-5 text-gray-600\">SVG files only</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Loader().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func Loader() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Loader_e5ea`,
		Function: `function __templ_Loader_e5ea(){var fileInput = document.getElementById('file-upload');
    var imagePreview = document.getElementById('image-preview');

    fileInput.addEventListener('change', function(e) {
        handleFiles(e.target.files); // Adjusted to handle event target files
    }, false);

    function handleFiles(files) {
        if (files.length > 0) {
            var file = files[0]; // Assuming single file upload, adjust as needed
            if (file.type === "image/svg+xml") {
                var reader = new FileReader();
                reader.onload = function (e) {
                    imagePreview.innerHTML = ` + "`" + `<img src="${e.target.result}" class="image-preview" alt="Uploaded Image Preview"/>` + "`" + `; // Display the SVG
                };
                reader.readAsDataURL(file);
            } else {
                imagePreview.innerHTML = "Please upload an SVG file.";
            }
        }
    }
}`,
		Call:       templ.SafeScript(`__templ_Loader_e5ea`),
		CallInline: templ.SafeScriptInline(`__templ_Loader_e5ea`),
	}
}
